In [8]:
#!/usr/bin/env jupyter notebook

'''
@Filename: kcdb_importer.py
@Description: This is the notebook to opreating the raw data from kcwiki api and then import the data to kcdb
'''

import pandas as pd
import kcdb
import ast

In [4]:
'''
Read the csv files from kcwiki api.
The path is "C:/Users/secar/OneDrive/oregairu/yukinoshita/kcdb/rawdata/apidata"
'''

df_ship = pd.read_csv('rawdata/apidata/ship.csv')
df_ship_stats = pd.read_csv('rawdata/apidata/ship_stats.csv')
df_slotitems = pd.read_csv('rawdata/apidata/slotitems.csv')
df_slotitems_type = pd.read_csv('rawdata/apidata/slotitems_type.csv')
df_slotitems_detail = pd.read_csv('rawdata/apidata/slotitems_detail.csv')

In [35]:
'''
Read the ship data and merge the ship stats with ship names through id.
'''

df_ship_detail = pd.merge(df_ship, df_ship_stats, on='id', how='right')
df_ship_detail = df_ship_detail.drop(['Unnamed: 0_x', 'Unnamed: 0_y', 'chinese_name', 'stype_name_chinese'], axis=1)
# df_ship_detail

,id,name,sort_no,stype,after_ship_id,filename,wiki_id,stype_name,can_drop,taik,...,tais,slot_num,max_eq,after_fuel,after_bull,fuel_max,bull_max,broken,pow_up,build_time
0,1,睦月,31.0,2,254.0,snohitatusbk,031,駆逐艦,True,"[13, 24]",...,16.0,2,"[0, 0, 0, 0, 0]",100.0,100.0,15.0,15.0,"[1, 1, 4, 0]","[1, 1, 0, 0]",18.0
1,2,如月,32.0,2,255.0,wujywbyjntbp,032,駆逐艦,True,"[13, 24]",...,16.0,2,"[0, 0, 0, 0, 0]",100.0,100.0,15.0,15.0,"[1, 1, 4, 0]","[0, 1, 0, 0]",18.0
2,6,長月,35.0,2,258.0,kksiqffpclxh,035,駆逐艦,True,"[13, 24]",...,16.0,2,"[0, 0, 0, 0, 0]",100.0,100.0,15.0,15.0,"[1, 1, 4, 0]","[0, 1, 0, 0]",18.0
3,7,三日月,37.0,2,260.0,ujhxqqlcorxv,037,駆逐艦,True,"[13, 24]",...,16.0,2,"[0, 0, 0, 0, 0]",100.0,100.0,15.0,15.0,"[1, 1, 4, 0]","[0, 1, 0, 0]",18.0
4,9,吹雪,11.0,2,201.0,gyckjmemgqoe,011,駆逐艦,True,"[15, 29]",...,20.0,2,"[0, 0, 0, 0, 0]",100.0,100.0,15.0,20.0,"[1, 1, 5, 0]","[1, 1, 0, 0]",20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1617,2257,深海珊瑚海水鬼,NaN,11,NaN,vmuppedtsgvw,NaN,正規空母,False,NaN,...,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1618,2258,深海珊瑚海水鬼,NaN,11,NaN,deuwjqawbhln,NaN,正規空母,False,NaN,...,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1619,2259,深海珊瑚海水鬼-壊,NaN,11,NaN,isnmelrgkldb,NaN,正規空母,False,NaN,...,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1620,2260,深海珊瑚海水鬼-壊,NaN,11,NaN,bqyhibnuinxc,NaN,正規空母,False,NaN,...,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1621,2261,深海珊瑚海水鬼-壊,NaN,11,NaN,hpyoftbuinsb,NaN,正規空母,False,NaN,...,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
'''
Read the slotitems data and processing with stats string to dataframe.
Then merge to a new dataframe with slotitems' id, name, type and stats data
'''

df_slotitems_stats = df_slotitems_detail[['id', 'name', 'chinese_name', 'type','stats']]

df_slotitems_stats = pd.merge(df_slotitems_stats, df_slotitems, on='id', how='left')
df_slotitems_stats = df_slotitems_stats.drop(['Unnamed: 0', 'type_x', 'use_bull', 'name_y','chinese_name_y','chinese_name_x'], axis=1)
df_slotitems_stats = df_slotitems_stats.rename(columns={'name_x': 'name', 'type_y': 'type'})

df_slotitems_stats['stats'] = df_slotitems_stats['stats'].apply(ast.literal_eval)
stats_df = df_slotitems_stats['stats'].apply(pd.Series)
df_slotitems_stats = pd.concat([df_slotitems_stats.drop(columns='stats'), stats_df], axis=1)
# df_slotitems_stats

,id,name,sort_no,info,rare,type,type_name,souk,raik,saku,...,tyku,leng,raig,houg,raim,luck,taik,sakb,distance,cost
0,1,12cm単装砲,1,旧型の小型砲です。<br>旧型駆逐艦に標準的主砲として搭載されました。<br>装填・操砲も人...,0,1,小口径主砲,0.0,0.0,0.0,...,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN
1,2,12.7cm連装砲,2,艦隊型駆逐艦の主砲です。<br>防盾で全周を遮蔽、弾片や荒天対策を施しており、また動力操砲も...,0,1,小口径主砲,0.0,0.0,0.0,...,2.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,NaN,NaN
2,3,10cm連装高角砲,3,防空型駆逐艦の主砲です。画期的な長砲身半自動装填砲を動力砲塔に備えた「長10cm」と呼ばれた...,1,1,小口径主砲,0.0,0.0,0.0,...,7.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,NaN,NaN
3,4,14cm単装砲,4,巡洋艦の主砲や戦艦の副砲として独自開発された中距離砲です。<br>やや旧式化していますが、列...,0,2,中口径主砲,0.0,0.0,0.0,...,0.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,NaN,NaN
4,5,15.5cm三連装砲,5,条約下で保有数に制限のあった重巡を、火力を増強した強力な軽巡で補うために開発されました。<b...,0,2,中口径主砲,0.0,0.0,0.0,...,4.0,2.0,0.0,7.0,0.0,0.0,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,568,16inch三連装砲,0,NaN,5,3,大口径主砲,1.0,0.0,0.0,...,3.0,3.0,0.0,24.0,0.0,0.0,0.0,0.0,4.0,6.0
266,569,深海偵察飛行艇,0,NaN,4,10,水上偵察機,0.0,0.0,9.0,...,1.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,4.0,6.0
267,570,高速深海魚雷 mod.2,0,NaN,4,22,特殊潜航艇,0.0,0.0,0.0,...,0.0,1.0,13.0,0.0,0.0,0.0,0.0,0.0,4.0,6.0
268,571,深海水母小鬼機,0,NaN,5,11,水上爆撃機,4.0,0.0,8.0,...,11.0,4.0,0.0,4.0,0.0,0.0,0.0,0.0,4.0,6.0
269,572,深海熊猫艦戦,0,NaN,5,6,艦上戦闘機,8.0,0.0,0.0,...,18.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,4.0,6.0

In [37]:
'''
Put the ship data and slotitems data into kancolle db
'''

df_ship_detail.to_sql('ship_details', con=kcdb.engine(), if_exists='replace', index=False)
df_slotitems_stats.to_sql('slotitems_details', con=kcdb.engine(), if_exists='replace', index=False)

270